// Generated from: examples/trading_operations.lcx
// Language: go
// Generated on: Sun Mar 22 13:35:29 GTBST 2026
// This file is auto-generated by the DSL compiler
// Do not edit manually

// API: LCX Exchange v1.1.0
// Authentication: HMAC-SHA256
// Rate Limits: 25 req/sec (market), 5 req/sec (trading)

// Implementation for trading_operations in go
