(require :drakma)

(defun fetch_all_tickers ()
  (let ((url "https://exchange-api.lcx.com/api/tickers"))
    (drakma:http-request url)))
(defun get_ticker_for_pair (pair)
  (let ((url "https://exchange-api.lcx.com/api/ticker"))
    (drakma:http-request url)))
(defun fetch_all_pairs ()
  (let ((url "https://exchange-api.lcx.com/api/pairs"))
    (drakma:http-request url)))
(defun get_pair_info (pair_symbol)
  (let ((url "https://exchange-api.lcx.com/api/pair/BTC/USDC"))
    (drakma:http-request url)))
(defun get_order_book (pair)
  (let ((url "https://exchange-api.lcx.com/api/book"))
    (drakma:http-request url)))
(defun get_recent_trades (pair, offset)
  (let ((url "https://exchange-api.lcx.com/api/trades"))
    (drakma:http-request url)))
(defun get_candle_data (pair, resolution, from_ts, to_ts)
  (let ((url "https://api-kline.lcx.com/v1/market/kline"))
    (drakma:http-request url)))
(defun market_overview ()
  (let ((url "https://exchange-api.lcx.com/api/book"))
    (drakma:http-request url)))
# Workflow: MarketOverview (sequence)

(defun get_trades ()
  (let ((url "https://exchange-api.lcx.com/api/trades"))
    (drakma:http-request url)))
# None method not supported for lisp
